---
global:
  writeToFile: false
  indexerConfig:
    enabled: ${INDEXING}
    esServers: ["${ES_SERVER}"]
    insecureSkipVerify: true
    defaultIndex: ${ES_INDEX}
    type: elastic
  measurements:
    - name: podLatency
      esIndex: ${ES_INDEX}
{{ if eq .PPROF_COLLECTION "True" }}
    - name: pprof
      pprofInterval: {{ .PPROF_COLLECTION_INTERVAL }}
      pprofDirectory: /tmp/pprof-data
      pprofTargets:

      - name: kube-apiserver-cpu
        namespace: "openshift-kube-apiserver"
        labelSelector: {app: openshift-kube-apiserver}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:6443/debug/pprof/profile?timeout=30

      - name: kube-apiserver-heap
        namespace: "openshift-kube-apiserver"
        labelSelector: {app: openshift-kube-apiserver}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:6443/debug/pprof/heap

      - name: etcd-heap
        namespace: "openshift-etcd"
        labelSelector: {app: etcd}
        cert: {{ .CERTIFICATE }}
        key: {{ .PRIVATE_KEY }}
        url: https://localhost:2379/debug/pprof/heap

      - name: etcd-cpu
        namespace: "openshift-etcd"
        labelSelector: {app: etcd}
        cert: {{ .CERTIFICATE }}
        key: {{ .PRIVATE_KEY }}
        url: https://localhost:2379/debug/pprof/profile?timeout=30

      - name: ovnkube-heap
        namespace: openshift-ovn-kubernetes
        labelSelector: {app: ovnkube-master}
        url: https://localhost:29102/debug/pprof/heap

      - name: ovnkube-cpu
        namespace: openshift-ovn-kubernetes
        labelSelector: {app: ovnkube-master}
        url: https://localhost:29102/debug/pprof/profile?timeout=30
{{ end }}
jobs:
  - name: node-density-cni
    jobIterations: ${TEST_JOB_ITERATIONS}
    qps: ${QPS}
    burst: ${BURST}
    namespacedIterations: false
    namespace: ${UUID}
    podWait: ${POD_WAIT}
    cleanup: ${CLEANUP}
    waitFor: ${WAIT_FOR}
    waitWhenFinished: ${WAIT_WHEN_FINISHED}
    verifyObjects: ${VERIFY_OBJECTS}
    errorOnVerify: ${ERROR_ON_VERIFY}
    maxWaitTimeout: ${MAX_WAIT_TIMEOUT}
    preLoadImages: ${PRELOAD_IMAGES}
    preLoadPeriod: ${PRELOAD_PERIOD}
    objects:

      - objectTemplate: webserver-deployment.yml
        replicas: 1
        inputVars:
          nodeSelector: "${POD_NODE_SELECTOR}"

      - objectTemplate: webserver-service.yml
        replicas: 1

      - objectTemplate: curl-deployment.yml
        replicas: 1
        inputVars:
          nodeSelector: "${POD_NODE_SELECTOR}"

